name: Build and Deploy Vue.js App to GitHub Pages

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Selenium and Chromedriver
        run: |
          npm install selenium-webdriver
          npm install chromedriver

      - name: Run Selenium tests
        run: npm run test:selenium

      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: selenium-artifacts
          path: '*.png'
