name: Maplebear B2C Staging Test

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Selenium and Chromedriver
        run: |
          npm install selenium-webdriver
          npm install chromedriver
          npm install pdfkit

      - name: Run Selenium tests
        env:
          ADMIN_LOGIN_USERNAME: ${{ secrets.ADMIN_LOGIN_USERNAME }}
          ADMIN_LOGIN_PASSWORD: ${{ secrets.ADMIN_LOGIN_PASSWORD }}
        run: npm run test:selenium

      - name: Generate PDF from screenshots
        run: node tests/generate-pdf.js

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: selenium-artifacts
          path: |
            screenshots/
            test-report.pdf
